### PR TITLE
Added fix for brewing stands

### PR DESCRIPTION
**Pull request by Rayzr522**
It was very simple, figured I might as well PR really quick :)

### CODE REVIEW

**Comment by gvlfm78** [comment]
Well you could have just committed directly

The real problem is that the jenkins server is down and I cannot figure out what rhcloud tried to do to it but it just won't start back up

**Comment by Rayzr522** [comment]
Haha, forgot I had write access. Silly me :p

As for openshift/rhcloud/whatever, I believe I got an email a while ago from them saying they were phasing out their OpenShift 2 system, which was the free one. So I think you may have just lost your Jenkins server :\

**Comment by gvlfm78** [comment]
No I migrated to openshift v3 a while ago but some image change redeployment of sorts caused it to go down and never start again

**Comment by Rayzr522** [comment]
Oh, fun >_>

Is OpenShift v3 still free?

**Comment by gvlfm78** [comment]
Yes but you can only really have one server per account because you are limited to one 'persistent storage'

In the meantime they have changed something which made Jenkins work again for me... after nuking it entirely and recreating it a couple of times...

**Pull request merged**
